# Site settings
title: "Jelly"
email: 651247149@qq.com
description: "我的博客"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "2010年到现在已经5年了，也要总结下自己的所得，时间过的太快了，项目也做了不少，可是缺少累计，进步一直不大..."
title_image: ""
google_analytics: ""
disqus_account: cartenoire
github_repository: https://github.com/jellygd
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
